<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<select id='list'>
<!-- <option value=''> select </option> -->
<option value='Australia'> Australia </option>
<option value='Afghanistan'> Afghanistan </option>
<option value='Albania'> Albania </option>
<option value='Algeria'> Algeria </option>
<option value='Andorra'> Andorra </option>
<option value='Angola'> Angola </option>
<option value='Anguilla'> Anguilla </option>
<option value='Antigua & Barbuda'> Antigua & Barbuda </option>
<option value='Argentina'> Argentina </option>
<option value='Armenia'> Armenia </option>
<option value='Austria'> Austria </option>
<option value='Azerbaijan'> Azerbaijan </option>
<option value='Bahamas'> Bahamas </option>
<option value='Bahrain'> Bahrain </option>
<option value='Bangladesh'> Bangladesh </option>
<option value='Barbados'> Barbados </option>
<option value='Belarus'> Belarus </option>
<option value='Belgium'> Belgium </option>
<option value='Belize'> Belize </option>
<option value='Benin'> Benin </option>
<option value='Bermuda'> Bermuda </option>
<option value='Bhutan'> Bhutan </option>
<option value='Bolivia'> Bolivia </option>
<option value='Bosnia & Herzegovina'> Bosnia & Herzegovina </option>
<option value='Botswana'> Botswana </option>
<option value='Brazil'> Brazil </option>
<option value='Brunei'> Brunei </option>
<option value='Bulgaria'> Bulgaria </option>
<option value='Burkina Faso'> Burkina Faso </option>
<option value='Burundi'> Burundi </option>
<option value='Cambodia'> Cambodia </option>
<option value='Cameroon'> Cameroon </option>
<option value='Canada'> Canada </option>
<option value='Cape Verde'> Cape Verde </option>
<option value='Cayman Islands'> Cayman Islands </option>
<option value='Central African Republic'> Central African Republic </option>
<option value='Chad'> Chad </option>
<option value='Chile'> Chile </option>
<option value='China'> China </option>
<option value='Colombia'> Colombia </option>
<option value='Comoros'> Comoros </option>
<option value='Congo'> Congo </option>
<option value='Congo Democratic Republic'> Congo Democratic Republic </option>
<option value='Cook Islands'> Cook Islands </option>
<option value='Costa Rica'> Costa Rica </option>
<option value='Croatia'> Croatia </option>
<option value='Cuba'> Cuba </option>
<option value='Cyprus'> Cyprus </option>
<option value='Czech Republic'> Czech Republic </option>
<option value='Denmark'> Denmark </option>
<option value='Djibouti'> Djibouti </option>
<option value='Dominica'> Dominica </option>
<option value='Dominican Republic'> Dominican Republic </option>
<option value='East Timor'> East Timor </option>
<option value='Ecuador'> Ecuador </option>
<option value='Egypt'> Egypt </option>
<option value='El Salvador'> El Salvador </option>
<option value='United Kingdom'> England </option>
<option value='Equatorial Guinea'> Equatorial Guinea </option>
<option value='Eritrea'> Eritrea </option>
<option value='Estonia'> Estonia </option>
<option value='Ethiopia'> Ethiopia </option>
<option value='Faeroe Islands'> Faeroe Islands </option>
<option value='Falkland Islands'> Falkland Islands </option>
<option value='Fiji'> Fiji </option>
<option value='Finland'> Finland </option>
<option value='France'> France </option>
<option value='French Guiana'> French Guiana </option>
<option value='French Polynesia'> French Polynesia </option>
<option value='Gabon'> Gabon </option>
<option value='Gambia'> Gambia </option>
<option value='Georgi'> Georgia (Europe)</option>
<option value='Germany'> Germany </option>
<option value='Ghana'> Ghana </option>
<option value='Gibraltar'> Gibraltar </option>
<option value='Greece'> Greece </option>
<option value='Greenland'> Greenland </option>
<option value='Grenada'> Grenada </option>
<option value='Guadeloupe'> Guadeloupe </option>
<option value='Guam'> Guam </option>
<option value='Guatemala'> Guatemala </option>
<option value='Guernsey'> Guernsey </option>
<option value='Guinea'> Guinea </option>
<option value='Guinea-Bissau'> Guinea-Bissau </option>
<option value='Guyana'> Guyana </option>
<option value='Haiti'> Haiti </option>
<option value='Honduras'> Honduras </option>
<option value='Hungary'> Hungary </option>
<option value='Iceland'> Iceland </option>
<option value='India'> India </option>
<option value='Indonesia'> Indonesia </option>
<option value='Iran'> Iran </option>
<option value='Iraq'> Iraq </option>
<option value='Ireland'> Ireland </option>
<option value='Israel'> Israel </option>
<option value='Italy'> Italy </option>
<option value='Ivory Coast'> Ivory Coast </option>
<option value='Jamaica'> Jamaica </option>
<option value='Japan'> Japan </option>
<option value='Jersey'> Jersey </option>
<option value='Jordan'> Jordan </option>
<option value='Kazakhstan'> Kazakhstan </option>
<option value='Kenya'> Kenya </option>
<option value='Kiribati'> Kiribati </option>
<option value='Korea, North'> Korea, North </option>
<option value='Korea, South'> Korea, South </option>
<option value='Kuwait'> Kuwait </option>
<option value='Kyrgyzstan'> Kyrgyzstan </option>
<option value='Laos'> Laos </option>
<option value='Latvia'> Latvia </option>
<option value='Lebanon'> Lebanon </option>
<option value='Lesotho'> Lesotho </option>
<option value='Liberia'> Liberia </option>
<option value='Libya'> Libya </option>
<option value='Liechtenstein'> Liechtenstein </option>
<option value='Lithuania'> Lithuania </option>
<option value='Luxembourg'> Luxembourg </option>
<option value='Macedonia'> Macedonia </option>
<option value='Madagascar'> Madagascar </option>
<option value='Malawi'> Malawi </option>
<option value='Malaysia'> Malaysia </option>
<option value='Maldives'> Maldives </option>
<option value='Mali'> Mali </option>
<option value='Malta'> Malta </option>
<option value='Man, Isle of'> Man, Isle of </option>
<option value='Marshall Islands'> Marshall Islands </option>
<option value='Martinique'> Martinique </option>
<option value='Mauritania'> Mauritania </option>
<option value='Mauritius'> Mauritius </option>
<option value='Mayotte'> Mayotte </option>
<option value='Mexico'> Mexico </option>
<option value='Micronesia'> Micronesia </option>
<option value='Midway Islands'> Midway Islands </option>
<option value='Moldova'> Moldova </option>
<option value='Monaco'> Monaco </option>
<option value='Mongolia'> Mongolia </option>
<option value='Montserrat'> Montserrat </option>
<option value='Morocco'> Morocco </option>
<option value='Mozambique'> Mozambique </option>
<option value='Myanmar'> Myanmar </option>
<option value='Namibia'> Namibia </option>
<option value='Nauru'> Nauru </option>
<option value='Nepal'> Nepal </option>
<option value='Netherlands'> Netherlands </option>
<option value='Netherlands Antilles'> Netherlands Antilles </option>
<option value='New Caledonia'> New Caledonia </option>
<option value='New Zealand'> New Zealand </option>
<option value='Nicaragua'> Nicaragua </option>
<option value='Niger'> Niger </option>
<option value='Nigeria'> Nigeria </option>
<option value='Niue'> Niue </option>
<option value='Norfolk Island'> Norfolk Island </option>
<option value='Northern Mariana Islands'> Northern Mariana Islands </option>
<option value='Norway'> Norway </option>
<option value='Oman'> Oman </option>
<option value='Pakistan'> Pakistan </option>
<option value='Palau'> Palau </option>
<option value='Panama'> Panama </option>
<option value='Papua New Guinea'> Papua New Guinea </option>
<option value='Paraguay'> Paraguay </option>
<option value='Peru'> Peru </option>
<option value='Philippines'> Philippines </option>
<option value='Pitcairn'> Pitcairn </option>
<option value='Poland'> Poland </option>
<option value='Portugal'> Portugal </option>
<option value='Qatar'> Qatar </option>
<option value='Reunion'> Reunion </option>
<option value='Romania'> Romania </option>
<option value='Russia'> Russia </option>
<option value='Rwanda'> Rwanda </option>
<option value='Saint Helena'> Saint Helena </option>
<option value='Saint Kitts-Nevis'> Saint Kitts-Nevis </option>
<option value='Saint Lucia'> Saint Lucia </option>
<option value='Saint Pierre and Miquelon'> Saint Pierre and Miquelon </option>
<option value='Saint Vincent and Grenadines'> Saint Vincent and Grenadines </option>
<option value='Samoa, American'> Samoa, American </option>
<option value='Samoa, Western'> Samoa, Western </option>
<option value='San Marino'> San Marino </option>
<option value='Sao Tome and Principe'> Sao Tome and Principe </option>
<option value='Saudi Arabia'> Saudi Arabia </option>
<option value='Senegal'> Senegal </option>
<option value='Seychelles'> Seychelles </option>
<option value='Sierra Leone'> Sierra Leone </option>
<option value='Singapore'> Singapore </option>
<option value='Slovakia'> Slovakia </option>
<option value='Slovenia'> Slovenia </option>
<option value='Solomon Islands'> Solomon Islands </option>
<option value='Somalia'> Somalia </option>
<option value='South Africa'> South Africa </option>
<option value='South Georgia'> South Georgia </option>
<option value='Spain'> Spain </option>
<option value='Sri Lanka'> Sri Lanka </option>
<option value='Sudan'> Sudan </option>
<option value='Suriname'> Suriname </option>
<option value='Swaziland'> Swaziland </option>
<option value='Sweden'> Sweden </option>
<option value='Switzerland'> Switzerland </option>
<option value='Syria'> Syria </option>
<option value='Taiwan'> Taiwan </option>
<option value='Tajikistan'> Tajikistan </option>
<option value='Tanzania'> Tanzania </option>
<option value='Thailand'> Thailand </option>
<option value='Togo'> Togo </option>
<option value='Tokelau Islands'> Tokelau Islands </option>
<option value='Tonga'> Tonga </option>
<option value='Trinidad and Tobago'> Trinidad and Tobago </option>
<option value='Tunisia'> Tunisia </option>
<option value='Turkey'> Turkey </option>
<option value='Turkmenistan'> Turkmenistan </option>
<option value='Turks and Caicos'> Turks and Caicos </option>
<option value='Tuvalu'> Tuvalu </option>
<option value='Uganda'> Uganda </option>
<option value='Ukraine'> Ukraine </option>
<option value='United Arab Emirates'> United Arab Emirates </option>
<option value='Uruguay'> Uruguay </option>
<option value='Uzbekistan'> Uzbekistan </option>
<option value='Vanuatu'> Vanuatu </option>
<option value='Venezuela'> Venezuela </option>
<option value='Vietnam'> Vietnam </option>
<option value='Virgin Islands'> Virgin Islands </option>
<option value='Wake Island'> Wake Island </option>
<option value='Wallis and Futuna'> Wallis and Futuna </option>
<option value='Yemen'> Yemen </option>
<option value='Yugoslavia'> Yugoslavia </option>
<option value='Zambia'> Zambia </option>
<option value='Zimbabwe'> Zimbabwe </option>
<option value='Alabama'> Alabama </option>
<option value='Alaska'> Alaska </option>
<option value='Arizona'> Arizona </option>
<option value='Arkansas'> Arkansas </option>
<option value='California'> California </option>
<option value='Colorado'> Colorado </option>
<option value='Connecticut'> Connecticut </option>
<option value='Delaware'> Delaware </option>
<option value='Dist of Columbia'> Dist of Columbia </option>
<option value='Florida'> Florida </option>
<option value='Georgia'> Georgia </option>
<option value='Hawaii'> Hawaii </option>
<option value='Idaho'> Idaho </option>
<option value='Illinois'> Illinois </option>
<option value='Indiana'> Indiana </option>
<option value='Iowa'> Iowa </option>
<option value='Kansas'> Kansas </option>
<option value='Kentucky'> Kentucky </option>
<option value='Louisiana'> Louisiana </option>
<option value='Maine'> Maine </option>
<option value='Maryland'> Maryland </option>
<option value='Massachusetts'> Massachusetts </option>
<option value='Michigan'> Michigan </option>
<option value='Minnesota'> Minnesota </option>
<option value='Mississippi'> Mississippi </option>
<option value='Missouri'> Missouri </option>
<option value='Montana'> Montana </option>
<option value='Nebraska'> Nebraska </option>
<option value='Nevada'> Nevada </option>
<option value='New Hampshire'> New Hampshire </option>
<option value='New Jersey'> New Jersey </option>
<option value='New Mexico'> New Mexico </option>
<option value='New York'> New York </option>
<option value='North Carolina'> North Carolina </option>
<option value='North Dakota'> North Dakota </option>
<option value='Ohio'> Ohio </option>
<option value='Oklahoma'> Oklahoma </option>
<option value='Oregon'> Oregon </option>
<option value='Pennsylvania'> Pennsylvania </option>
<option value='Puerto Rico'> Puerto Rico </option>
<option value='Rhode Island'> Rhode Island </option>
<option value='South Carolina'> South Carolina </option>
<option value='South Dakota'> South Dakota </option>
<option value='Tennessee'> Tennessee </option>
<option value='Texas'> Texas </option>
<option value='Utah'> Utah </option>
<option value='United Kingdom'> United Kingdom </option>
<option value='United State'> United State </option>
<option value='Vermont'> Vermont </option>
<option value='Virginia'> Virginia </option>
<option value='Washington'> Washington </option>
<option value='West Virginia'> West Virginia </option>
<option value='Wisconsin'> Wisconsin </option>
<option value='Wyoming'> Wyoming </option>
</select>

<script type="text/javascript">

	var country = [];


	$("#list option").each(function()
	{
	   new_c = $(this).val();
		country.push(new_c);

	});

	console.log(country);
	
</script>